# Generated by Django 6.0.1 on 2026-01-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassLectureFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('file', models.FileField(upload_to='lecture_files/')),
                ('upload_date', models.DateTimeField(auto_now=True)),
                ('course', models.ManyToManyField(blank=True, to='course.course')),
            ],
        ),
        migrations.CreateModel(
            name='VideoLecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('video_url', models.CharField(max_length=255)),
                ('upload_date', models.DateTimeField(auto_now=True)),
                ('course', models.ManyToManyField(blank=True, to='course.course')),
            ],
        ),
    ]
